### PR TITLE
Rename spec/data.n3 as spec/data.ttl

### LINKED ISSUE #24: Rename spec/data.n3 as spec/data.ttl
Confusing file extension.

### PR DESCRIPTION
**Pull request by afs**
This resolves #24.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-results-xml/pull/29.html" title="Last updated on May 4, 2023, 3:12 PM UTC (accfec5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/sparql-results-xml/29/44803f7...accfec5.html" title="Last updated on May 4, 2023, 3:12 PM UTC (accfec5)">Diff</a>

### CODE REVIEW

**Comment by afs** [comment]
FPWD is now targeted for 16/May.

This PR does not have to go in - it does not really change much, it just seems neater to not use`.n3` for what is RDF Turtle.

I can find time to regenerate the FPWD for sparql-results-xml if it is a few days before 16/May (unless all of the docs have to be 
fixed at the last minute).

**Review by rubensworks — APPROVED** [review]
ttl makes more sense indeed!

**Review by domel — APPROVED** [review]

**Comment by afs** [comment]
(I'm not a editor on this doc)

Do the editors want this is the FPWD? (I'm happy either way)

**Comment by rubensworks** [comment]
@afs I don't have a big preference. If it's not too much effort for you, we could indeed include it.

Will merge this one in the meantime.

**Pull request merged**
